services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    restart: on-failure
    networks:
      - inception_network

  db:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      device: ${DB_DATA_PATH}
      o: 'bind'
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      device: ${WORDPRESS_FILES_PATH}
      o: 'bind'
